### ISSUE TITLE
Necesitamos un favicon 

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/kitcat#10]

**Comment by diegobeauroyre** [comment]
#11

**Comment by diegobeauroyre** [comment]
En chrome no jala el favicon.

**Comment by poguez** [comment]
Parece que ya.

![screen shot 2015-02-25 at 12 51 34 am](https://cloud.githubusercontent.com/assets/732015/6366256/80483d2e-bc88-11e4-8ed1-9feb4941c42e.png)
