### ISSUE TITLE
Agregar botón que redirija al form de encuesta para ser parte del directorio

### ISSUE THREAD

**Issue by jipster** [mxabierto/kitcat#103]
Aquí el link

http://goo.gl/forms/zAvhvSN9AP

https://docs.google.com/forms/d/1tZ21d0rGQJH52lJgz1q-j3VSNoEs2ahDqkgvzTU6ksw/edit?usp=sharing

**Comment by poguez** [comment]
YA se agregó en 6b6ee6f06704c3cd5807762d345222dcfdfd39df
