### ISSUE TITLE
Agregar a la sección del mapa "Estamos construyendo la experiencia de Mx Abierto"

### ISSUE THREAD

**Issue by paulinabustos** [mxabierto/kitcat#106]
Mientras construimos el nuevo sitio de MxAbierto queremos dejar un mensaje de "Estamos contruyendo la nueva Experiencia de la Red MX Abierto, pronto verás los cambios en esta página, por lo pronto déjanos un mensaje para unirte a la Red"

El únete debe ser una liga que te lleva a la siguiente forma: https://docs.google.com/a/codeandomexico.org/forms/d/1tZ21d0rGQJH52lJgz1q-j3VSNoEs2ahDqkgvzTU6ksw/viewform?c=0&w=1

**Comment by jipster** [comment]
Está perfecto @paulinabustos @poguez 

sólo dos cuestiones:

1. Hay que siempre decirles Red México Abierto
2. El únete que diga: "Únete al directorio"
