### ISSUE TITLE
Agregar "Recibe más información" para inscribirte a Newsletter

### ISSUE THREAD

**Issue by paulinabustos** [mxabierto/kitcat#115]

**Comment by poguez** [comment]
@jipster @alejandrardr necesitamos el html de la forma para suscribirse.

**Comment by paulinabustos** [comment]
@jipster @alejandrardr Debe estar en los settings de su cuenta.

**Comment by jipster** [comment]
será esto @paulinabustos @poguez ?


<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">

**Comment by jipster** [comment]
esto más bien @paulinabustos 



<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//mxabierto.us10.list-manage.com/subscribe/post?u=aee2b633eca6a653c0509a4c1&amp;id=03590929af" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Recibe más información</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Dirección de correo electrónico  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">Nombre  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-MMERGE3">Municipio, Estado, D.F. o Delegación  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="MMERGE3" class="required" id="mce-MMERGE3">
</div>
<div class="mc-field-group">
	<label for="mce-MMERGE2">Puesto  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="MMERGE2" class="required" id="mce-MMERGE2">
</div>
<div class="mc-field-group input-group">
    <strong>Email Format </strong>
    <ul><li><input type="radio" value="html" name="EMAILTYPE" id="mce-EMAILTYPE-0"><label for="mce-EMAILTYPE-0">html</label></li>
<li><input type="radio" value="text" name="EMAILTYPE" id="mce-EMAILTYPE-1"><label for="mce-EMAILTYPE-1">text</label></li>
</ul>
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_aee2b633eca6a653c0509a4c1_03590929af" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

**Comment by poguez** [comment]
¿Qué tal así @jipster @paulinabustos ?


![screen shot 2015-03-20 at 6 49 38 pm](https://cloud.githubusercontent.com/assets/732015/6763015/08a42c58-cf32-11e4-9b1f-4654b816a36b.png)
![screen shot 2015-03-20 at 6 50 16 pm](https://cloud.githubusercontent.com/assets/732015/6763017/0e80d644-cf32-11e4-9fe2-0524f8450b56.png)
