### ISSUE TITLE
Ponerle título al mapa: "Miembros actuales o activos o publicando datos"

### ISSUE THREAD

**Issue by jipster** [mxabierto/kitcat#123]
Estaría bien que hubiera una explicación de lo que trata de decir este mapa. 

Qué se les ocurre @paulinabustos @poguez ? Ciudades y Estados en datos.gob.mx o no sé
![image](https://cloud.githubusercontent.com/assets/5718530/6784021/d75f180c-d142-11e4-9806-b221ebd4fa03.png)

**Comment by poguez** [comment]
![screen shot 2015-03-23 at 10 30 30 am](https://cloud.githubusercontent.com/assets/732015/6784875/e5348570-d147-11e4-88e0-5d03daf843dc.png)

**Comment by poguez** [comment]
Algo así @jipster ?
