### ISSUE TITLE
Emparejar el navbar de datatron al de la red

### ISSUE THREAD

**Issue by rodowi** [mxabierto/kitcat#20]
![screen shot 2015-01-20 at 6 23 28 pm](https://cloud.githubusercontent.com/assets/705860/5829020/74f0bf8c-a0d1-11e4-9fa7-f7f6dd1e487c.png)

**Comment by poguez** [comment]
![screen shot 2015-01-20 at 6 32 28 pm](https://cloud.githubusercontent.com/assets/732015/5829100/bd97e7a0-a0d2-11e4-8c9c-f66f1d01cd79.png)
