### ISSUE TITLE
Copy nuevo en 'Inauguración' y flecha 

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/kitcat#29]
- [x] Copy nuevo: 

La Red MX Abierto se lanzará en el marco de las Jornadas Innovación Local para un México Abierto el próximo 19 y 20 de febrero en la Ciudad de México, en el Centro de Cultura Digital.

El encuentro incluirá conferencias magistrales, paneles de discusión y talleres de capacitación dirigidos a representantes de gobiernos municipales y estatales interesados en implementar procesos de publicación y uso de datos abiertos gubernamentales.

Como resultado de las jornadas, se seleccionarán las ciudades y estados que recibirán acompañamiento en su proceso de apertura de datos para acelerar su avance y así detonar un movimiento de innovación y apertura del sector público a nivel subnacional a través de la Red MX Abierto.

**Comment by juanpabloe** [comment]
saqué la flechita para otro issue.
el copy ya está live
