### ISSUE TITLE
No estaría mal agregar una guía para limpiar datos

### ISSUE THREAD

**Issue by rodowi** [mxabierto/kitcat#34]
P. ej. esta del ODI https://docs.google.com/a/theodi.org/document/d/1SsHaDcw7hgEkaKI-IypCw5dbQPuhNcOz3sV_wuaIJ8U/edit?usp=sharing

_habría que pedirles permiso para utilizarla ya que no le veo licencia_

**Comment by poguez** [comment]
Se hablará en las herramientas del kit.
