### ISSUE TITLE
Datatron con encuesta

### ISSUE THREAD

**Issue by juanpabloe** [mxabierto/kitcat#4]
- [x] Setup del fork del datatron
- [x] Configurar preguntas
- [x] Estilos de la Red MX Abierto
- [x] Subdominio que apunte a: https://polling-cmx.herokuapp.com/encuesta

Top Navbar links:
- [x] Acerca de (-> mxabierto.org)
- [x] Encuesta de Datos (-> encuesta.mxabierto.org)

**Comment by juanpabloe** [comment]
hover en un botón no debería cambiar el color a azul:
![screen shot 2015-01-13 at 7 54 50 pm](https://cloud.githubusercontent.com/assets/542209/5732796/1d5f0bca-9b5e-11e4-96a3-88de98d06605.png)

cc @poguez

**Comment by rodowi** [comment]
dónde están trabajando el fork del datatron?

**Comment by rodowi** [comment]
@diegobeauroyre sería bueno saber tu feedback de http://polling-cmx.herokuapp.com/encuesta

**Comment by diegobeauroyre** [comment]
Creo que faltaría:

- [ ] Container general 
- [ ] Que sepas que estás en la encuesta, puede ser con un título: "Encuesta"

**Comment by poguez** [comment]
A que te refiere con Container genera @diegobeauroyre ?

**Comment by diegobeauroyre** [comment]
@poguez Es el mismo issue que en https://github.com/mxabierto/kitcat/issues/8

Necesitamos un container max-width para que no se hagan los botones gigantes

**Comment by rodowi** [comment]
Los botones se comportan diferente a http://datatron.herokuapp.com/

- [ ] quitar hover effect
- [ ] ajustar width de los botones
