### ISSUE TITLE
Cambiar ancho de botones en encuesta

### ISSUE THREAD

**Issue by tlacoyodefrijol** [mxabierto/kitcat#57]

**Comment by poguez** [comment]
![screen shot 2015-02-09 at 10 09 29 pm](https://cloud.githubusercontent.com/assets/732015/6121414/68d62fb6-b0a8-11e4-8ea5-3f07a7aafbe8.png)
Parece que así está mejor, ¿Qué les parece?.

**Comment by jipster** [comment]
Si, está mucho mejor. Me lo llevo.

**Comment by poguez** [comment]
:white_check_mark:
