### ISSUE TITLE
Sección de Agenda

### ISSUE THREAD

**Issue by paulinabustos** [mxabierto/kitcat#6]
Vamos a agregar una sección de Agenda, que sea otro link en el header. La sección tendrá: 

- La descripción del evento: 

El lanzamiento oficial de la Red MX Abierto que se llevará a cabo en el marco de las  Jornadas Innovación Local para un México Abierto el próximo 19 y 20 de febrero en la Ciudad de México. 

Este encuentro tendrá lugar en el Centro de Cultura Digital ubicado en Paseo de Reforma s/n Esquina Lieja, Colonia Juárez. El programa del encuentro incluirá conferencias magistrales, paneles de discusión y talleres de capacitación dirigidos a representantes de gobiernos municipales y estatales interesados en comenzar o conocer más sobre procesos de promoción, publicación y uso de datos abiertos gubernamentales. 
Como resultado de las jornadas, se seleccionarán las ciudades y estados que recibirán acompañamiento en su proceso de apertura de datos para acelerar su avance y así detonar un movimiento de innovación y apertura del sector público a nivel subnacional a través de la Red MX_Abierto.

- La agenda: https://docs.google.com/a/codeandomexico.org/file/d/0B6yTLTkX8c09S0ZfMFZ3Q0NSa2hIX2NMdzctazJ2VFl4NFhj/edit

**Comment by rodowi** [comment]
La tabla de la agenda será con el estilo de http://condatos.org/

**Comment by diegobeauroyre** [comment]
Por ahora sin links.
