### ISSUE TITLE
Tabla es resposiva en móviles 

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/kitcat#65]
![screen shot 2015-02-12 at 6 26 37 pm](https://cloud.githubusercontent.com/assets/6226604/6180006/f6843b08-b2e4-11e4-8b69-cfd31c9a7a4f.png)

**Comment by poguez** [comment]
Ummm, esto ya estaba responsive.

**Comment by poguez** [comment]
My bad, ha cambiado un chorro la agenda :worried: 
Jaja mero está :dancers:

**Comment by poguez** [comment]
Review @diegobeauroyre plz   

La tercera columna lo mandamos en la versión de pantallas <768px a una fila independiente.:grin:

![screen shot 2015-02-13 at 12 20 30 am](https://cloud.githubusercontent.com/assets/732015/6183108/37bbeb80-b316-11e4-8646-e861f6ec80b4.png)

**Comment by poguez** [comment]
Hasta este ancho se ve óptimo.

![screen shot 2015-02-13 at 12 25 18 am](https://cloud.githubusercontent.com/assets/732015/6183153/d923707e-b316-11e4-82dd-af3550cca06a.png)

**Comment by poguez** [comment]
Los cambios aún no están arriba @jipster aquí es donde esta la muestra de como se ve.

**Comment by jipster** [comment]
Ah Lol. #amateur

Con que se vean el taller 2 & 3 del mismo peso, creo que estamos good to go.

**Comment by poguez** [comment]
@jipster si puedes dale una checada online para cerrar el issue.

**Comment by jipster** [comment]
Hay poquito issue
