### ISSUE TITLE
Rediseño UX

### ISSUE THREAD

**Issue by rodowi** [mxabierto/kitcat#7]
- [x] Cambiar el call to action de registro, para que quede claro que es un registro a un evento, no al sitio
- [x] Cambiar estilo de los botones

**Comment by diegobeauroyre** [comment]
![red_mx_a_web-01-01](https://cloud.githubusercontent.com/assets/6226604/5809627/4d18f618-a000-11e4-86d8-1d58b752ac3e.png)

**Comment by poguez** [comment]
@diegobeauroyre digamos que inauguración queda en:
'http://mxabierto.org/inauguracion.html' para que lo ponga también en el navbar de la app de la encuesta.

**Comment by diegobeauroyre** [comment]
ok.

Acá está la actualización:

![red_mx_a_web-01-02](https://cloud.githubusercontent.com/assets/6226604/5809931/3c85307e-a004-11e4-9941-16161a3303e3.png)

**Comment by juanpabloe** [comment]
Listo con#16
