### ISSUE TITLE
Poner un container general 

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/kitcat#8]
En widescreen pasa esto:

![screen shot 2015-01-19 at 1 58 14 pm](https://cloud.githubusercontent.com/assets/6226604/5806919/5420d8d0-9fe3-11e4-9803-9cab4056ccd0.png)

**Comment by poguez** [comment]
@diegobeauroyre tienes alguna sugerencia visual para que la pase a css?

**Comment by diegobeauroyre** [comment]
@poguez Te pongo acá un screenshot con el grid que usé, el max-width es de 960 px.

![screen shot 2015-01-19 at 6 02 42 pm](https://cloud.githubusercontent.com/assets/6226604/5810051/9d6561ba-a005-11e4-87e4-33f7dfbdb7f6.png)

**Comment by poguez** [comment]
Listo, ver #12

**Comment by poguez** [comment]
Se actualizó el pull request con un rebase ver #14

**Comment by juanpabloe** [comment]
:+1: yeah
