### ISSUE TITLE
Guía

### ISSUE THREAD

**Issue by jipster** [mxabierto/kitcat#82]
La guía podría estar en el mismo formato del playbook que se está usando para APF? 

@rodowi @juanpabloe @poguez

**Comment by jipster** [comment]
Hola han podido ver que la guía quede como la del decreto? Cómo qué día podríamos tener una versión de esto? saludos

http://mxabierto.github.io/guia/

**Comment by poguez** [comment]
Se va a ver en la siguiente versión.
