### ISSUE TITLE
Quitar el registro

### ISSUE THREAD

**Issue by jipster** [mxabierto/kitcat#84]
Habría que quitar la pestaña del registro y el link de la pantalla principal.

En el lugar donde se dice del evento, con fondo verde, invitamos la gente a entrar a la encuesta de datos, a la guía y a contactarnos si tienen alguna duda en mexico.abierto@datos.gob.mx

cómo ven? @paulinabustos

**Comment by paulinabustos** [comment]
Me gusta la idea @jipster. 

Lo que podemos hacer es cambiar del menú "Registro" por "Contacto" y la sección verde, creo que sería mejor quitarla y dejar que la primera sección sea "Objetvos", ¿te parece?

**Comment by jipster** [comment]
Va.
Quitamos el registro dejamos los objetivos & @diegobeauroyre  va a estar  mandando input sobre como transitar a la página

**Comment by jipster** [comment]
Hola! Se puede bajar el registro pronto :dancers:?

Ya veremos lo del rediseño del site en la semana, pero eso si está medio confuso. 

También quería ver si podemos pensar en una forma en donde podamos integrar el video de intro de Red MX Abierto http://youtu.be/lerkvbhQGkc, el de cierre http://youtu.be/Edy7IoruBeo y finalmente la opción de ver el video del evento completo http://youtu.be/385TL33Yup0.
