### ISSUE TITLE
Ajustar padding en Navbar

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/kitcat#85]
![screen shot 2015-02-23 at 10 03 50 am](https://cloud.githubusercontent.com/assets/6226604/6331166/4d2affa8-bb43-11e4-8aab-3dc2af018af9.png)

Están disparejos los paddings.

**Comment by poguez** [comment]
YA está ajustado en 868b82106dfb8c0242b3f48478c86b3005c5f418
