### ISSUE TITLE
updatear el Copy datapoll red méxico abierto 

### ISSUE THREAD

**Issue by jipster** [mxabierto/kitcat#86]
Creo que debería de decir: "¿Qué información de gobierno te gustaría conocer?"

y es necesario agregar una pequeña descripción explicando de qué se trata esta encuesta:

Red México Abierto es el primer ejercicio a nivel nacional para la colaboración y aprendizaje entre pares, con el objetivo de impulsar la publicación y utilización de datos abiertos en todos los niveles de gobierno. 

Para llegar a un modelo comprensivo y que responda a las necesidades reales de los gobiernos municipales y estatales de México nos interesa conocer cuáles temas son los que usuarios y administradores de datos encuentran más relevantes. 

![screen shot 2015-02-24 at 11 03 53](https://cloud.githubusercontent.com/assets/5718530/6354404/e463a5b0-bc14-11e4-8b21-ec2a2de65362.png)

**Comment by poguez** [comment]
![screen shot 2015-02-25 at 1 12 00 pm](https://cloud.githubusercontent.com/assets/732015/6378290/fcf30c20-bcef-11e4-94bd-6aa676891479.png)

**Comment by poguez** [comment]
¿La compras @jipster? :cake:

**Comment by jipster** [comment]
uy, casi compro @poguez 

nomás pondría el primer párrafo de "Red México ...." debajo del logo y el otro párrafo debajo de la encuesta.

gracias mil :8ball:

**Comment by poguez** [comment]
![screen shot 2015-02-25 at 2 16 38 pm](https://cloud.githubusercontent.com/assets/732015/6379574/f619d362-bcf8-11e4-81b1-1d8f62b6625d.png)
