### ISSUE TITLE
Agregar leyenda "Este sitio es adminsitrado por la Coordinación de Red México Abierto"

### ISSUE THREAD

**Issue by alejandrardr** [mxabierto/kitcat#97]
Creo que hasta abajo de la página o en algún lado visible.

**Comment by jipster** [comment]
Ah, tenemos que poner que lo administramos nosotros o Codeando?

**Comment by alejandrardr** [comment]
Tenemos que poner la Coordinación de Red México Abierto que incluye a nosotros, Codeando y Función Púlica

**Comment by jipster** [comment]
Ah, ya entendí.... buenísimo

**Comment by poguez** [comment]
El footer se ajustará a las organizaciones en la siguiente versión.
